version: 2

updates:
- package-ecosystem: github-actions
  # Workflow files stored in the default location of `.github/workflows`
  directory: "/"
  schedule:
    interval: daily

- package-ecosystem: docker
  directory: "/.github/actions/api-docs"
  schedule:
    interval: daily

- package-ecosystem: docker
  directory: "/api-docs"
  schedule:
    interval: daily

- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily

- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily

- package-ecosystem: docker
  directory: "/tools"
  schedule:
    interval: daily

- package-ecosystem: composer
  directory: "/tools"
  schedule:
    interval: daily
