version: 2

updates:
- package-ecosystem: github-actions
  # Workflow files stored in the default location of `.github/workflows`
  directory: "/"
  schedule:
    interval: daily
  rebase-strategy: disabled

- package-ecosystem: docker
  directories:
    - "/"
    - "/.github/actions/api-docs"
    - "/api-docs"
  schedule:
    interval: daily
  rebase-strategy: disabled
  groups:
    php-updates:
      patterns:
        - "php"

- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
  rebase-strategy: disabled

- package-ecosystem: docker-compose
  directories:
    - "/"
    - "/test"
    - "/live"
  schedule:
    interval: daily
  rebase-strategy: disabled
