build_failure_conditions:
  # Fail on any new issues (note that 'issues.new.exists' does not work)
  - 'issues.severity(>= INFO).new.exists'

build:
  image: default-bionic
  environment:
    php: 8.1.3
  nodes:
    analysis:
      project_setup:
        override:
          - cp config/config.specific.sample.php config/config.specific.php

filter:
  excluded_paths:
    - 'tests/*'
