UPDATE weapon SET price = 340350 WHERE name = 'Holy Hand Grenade';
UPDATE weapon SET price = 345500, accuracy = 35 WHERE name = 'Planetary Pulse Laser';
UPDATE weapon SET price = 219750 WHERE name = 'Huge Pulse Laser';
UPDATE weapon SET price = 220000 WHERE name = 'Nijarin Claymore Missile';
UPDATE weapon SET price = 216000 WHERE name = 'Creonti "Big Daddy"';
UPDATE weapon SET price = 210000 WHERE name = 'Thevian Shield Disperser';
UPDATE weapon SET price = 185500 WHERE name = 'Little Junior Torpedo';
UPDATE weapon SET price = 168000 WHERE name = 'Human Harmonic Disruptor';
UPDATE weapon SET price = 166000 WHERE name = 'Alskant Focused Laser';
UPDATE weapon SET price = 177000 WHERE name = 'Big Momma Torpedo Launcher';
UPDATE weapon SET price = 167500 WHERE name = 'WQ Human Shield Vaporizer';
UPDATE weapon SET price = 113750 WHERE name = 'Large Pulse Laser';
UPDATE weapon SET price = 104000 WHERE name = 'Salvene EM Flux Cannon';
UPDATE weapon SET price = 102500 WHERE name = 'Human Photon Torpedo';
UPDATE weapon SET price = 100000 WHERE name = 'Nijarin Ion Phaser Beam';
UPDATE weapon SET price = 101000 WHERE name = 'Insanely Large Laser';
UPDATE weapon SET price = 97000 WHERE name = 'Photon Torpedo';
UPDATE weapon SET price = 86500 WHERE name = 'Creonti Mole Missile';
UPDATE weapon SET price = 86500 WHERE name = 'Creonti Shield Sucker';
UPDATE weapon SET price = 82750 WHERE name = 'Thevian Assault Laser';
UPDATE weapon SET price = 84000 WHERE name = 'Alskant Space Flechette';
UPDATE weapon SET price = 80000 WHERE name = 'Ik-Thorne Burst Laser System';
UPDATE weapon SET price = 79500 WHERE name = 'WQ Human Multi-Phase Laser';
UPDATE weapon SET price = 76000 WHERE name = 'Pulse Laser';
UPDATE weapon SET price = 59000 WHERE name = 'Nijarin Ion Disrupter';
UPDATE weapon SET price = 59000 WHERE name = 'Large Laser';
UPDATE weapon SET price = 53500 WHERE name = 'Alskant Pulse-Fist Missile';
UPDATE weapon SET price = 50000 WHERE name = 'Salvene Flux Resonator';
UPDATE weapon SET price = 51000 WHERE name = 'Projectile Cannon Lvl 4';
UPDATE weapon SET price = 49750 WHERE name = 'Thevian Flux Missile';
UPDATE weapon SET price = 49500 WHERE name = 'Creonti Particle Cannon';
UPDATE weapon SET price = 47250 WHERE name = 'Human Space Shotgun';
UPDATE weapon SET price = 47000 WHERE name = 'Ik-Thorne Cluster Missile';
UPDATE weapon SET price = 46500 WHERE name = 'Salvene Frag Missile';
UPDATE weapon SET price = 46000 WHERE name = 'Alskant Anti-Shield System';
UPDATE weapon SET price = 47000 WHERE name = 'Torpedo Launcher';
UPDATE weapon SET price = 44500 WHERE name = 'WQ Human Flechette Cannon';
UPDATE weapon SET price = 45000 WHERE name = 'Advanced Shield Disruptor';
UPDATE weapon SET price = 42000 WHERE name = 'Anti-Ship Missile (Guided)';
UPDATE weapon SET price = 39500 WHERE name = 'Laser';
UPDATE weapon SET price = 37250 WHERE name = 'Projectile Cannon Lvl 3';
UPDATE weapon SET price = 34000 WHERE name = 'Ik-Thorne Accoustic Jammer';
UPDATE weapon SET price = 27500 WHERE name = 'Ik-Thorne Rapid Fire Cannon';
UPDATE weapon SET price = 28500 WHERE name = 'Anti-Ship Missile (Heat-Seeking)';
UPDATE weapon SET price = 22250 WHERE name = 'Thevian Rail Gun';
UPDATE weapon SET price = 22250 WHERE name = 'Anti-Ship Missile';
UPDATE weapon SET price = 22000 WHERE name = 'Projectile Cannon Lvl 2';
UPDATE weapon SET price = 20775 WHERE name = 'Nijarin Ion Pulse Phaser';
UPDATE weapon SET price = 18650 WHERE name = 'Shield Disruptor';
UPDATE weapon SET price = 13000 WHERE name = 'Projectile Cannon Lvl 1';
UPDATE weapon SET price = 13000 WHERE name = 'Small Laser';
