UPDATE weapon_type SET armour_damage = 260 WHERE weapon_name = 'Nuke';
UPDATE weapon_type SET shield_damage = 260 WHERE weapon_name = 'Holy Hand Grenade';
UPDATE weapon_type SET shield_damage = 130, armour_damage = 130 WHERE weapon_name = 'Planetary Pulse Laser';
UPDATE weapon_type SET accuracy = 81 WHERE weapon_name = 'Alskant Focused Laser';
UPDATE weapon_type SET accuracy = 32 WHERE weapon_name = 'Creonti "Big Daddy"';
UPDATE weapon_type SET accuracy = 82 WHERE weapon_name = 'Human Harmonic Disruptor';
UPDATE weapon_type SET shield_damage = 80, armour_damage = 80, accuracy = 50 WHERE weapon_name = 'Huge Pulse Laser';
UPDATE weapon_type SET armour_damage = 100, accuracy = 78 WHERE weapon_name = 'Little Junior Torpedo';
UPDATE weapon_type SET accuracy = 38 WHERE weapon_name = 'Big Momma Torpedo Launcher';
UPDATE weapon_type SET armour_damage = 175, accuracy = 46 WHERE weapon_name = 'Nijarin Claymore Missile';
UPDATE weapon_type SET accuracy = 46 WHERE weapon_name = 'Thevian Shield Disperser';
UPDATE weapon_type SET shield_damage = 250, accuracy = 32 WHERE weapon_name = 'WQ Human Shield Vaporizer';
UPDATE weapon_type SET armour_damage = 100, accuracy = 75 WHERE weapon_name = 'Alskant Space Flechette';
UPDATE weapon_type SET armour_damage = 110 WHERE weapon_name = 'Creonti Mole Missile';
UPDATE weapon_type SET shield_damage = 110 WHERE weapon_name = 'Creonti Shield Sucker';
UPDATE weapon_type SET armour_damage = 175, accuracy = 42 WHERE weapon_name = 'Human Photon Torpedo';
UPDATE weapon_type SET armour_damage = 75, accuracy = 66 WHERE weapon_name = 'Human Multi-Phase Laser';
UPDATE weapon_type SET shield_damage = 60, armour_damage = 60, accuracy = 63 WHERE weapon_name = 'Ik-Thorne Burst Laser System';
UPDATE weapon_type SET accuracy = 60 WHERE weapon_name = 'Large Pulse Laser';
UPDATE weapon_type SET shield_damage = 110, armour_damage = 110, accuracy = 32 WHERE weapon_name = 'Insanely Large Laser';
UPDATE weapon_type SET armour_damage = 170, accuracy = 42 WHERE weapon_name = 'Photon Torpedo';
UPDATE weapon_type SET accuracy = 93 WHERE weapon_name = 'Newbie Pulse Laser';
UPDATE weapon_type SET accuracy = 93 WHERE weapon_name = 'Pulse Laser';
UPDATE weapon_type SET shield_damage = 140, armour_damage = 30 WHERE weapon_name = 'Nijarin Ion Phaser Beam';
UPDATE weapon_type SET shield_damage = 115, accuracy = 46 WHERE weapon_name = 'Salvene EM Flux Cannon';
UPDATE weapon_type SET accuracy = 69 WHERE weapon_name = 'Salvene Chain Laser';
UPDATE weapon_type SET armour_damage = 120, accuracy = 54 WHERE weapon_name = 'Thevian Assault Laser';
UPDATE weapon_type SET shield_damage = 75, accuracy = 66 WHERE weapon_name = 'WQ Human Multi-Phase Laser';
UPDATE weapon_type SET shield_damage = 30, armour_damage = 90, accuracy = 58 WHERE weapon_name = 'Alskant Pulse-Fist Missile';
UPDATE weapon_type SET shield_damage = 90, accuracy = 77 WHERE weapon_name = 'Alskant Anti-Shield System';
UPDATE weapon_type SET shield_damage = 40, armour_damage = 40, accuracy = 88 WHERE weapon_name = 'Creonti Particle Cannon';
UPDATE weapon_type SET armour_damage = 75, accuracy = 93 WHERE weapon_name = 'Human Space Shotgun';
UPDATE weapon_type SET armour_damage = 110, accuracy = 63 WHERE weapon_name = 'Ik-Thorne Cluster Missile';
UPDATE weapon_type SET shield_damage = 75, accuracy = 92 WHERE weapon_name = 'Ik-Thorne Accoustic Jammer';
UPDATE weapon_type SET shield_damage = 55, armour_damage = 55, accuracy = 61 WHERE weapon_name = 'Large Laser';
UPDATE weapon_type SET armour_damage = 125, accuracy = 53 WHERE weapon_name = 'Projectile Cannon Lvl 4';
UPDATE weapon_type SET armour_damage = 175, accuracy = 37 WHERE weapon_name = 'Torpedo Launcher';
UPDATE weapon_type SET shield_damage = 100, accuracy = 67 WHERE weapon_name = 'Advanced Shield Disruptor';
UPDATE weapon_type SET armour_damage = 70, accuracy = 99 WHERE weapon_name = 'Anti-Ship Missile (Guided)';
UPDATE weapon_type SET shield_damage = 40, armour_damage = 40, accuracy = 85 WHERE weapon_name = 'Laser';
UPDATE weapon_type SET armour_damage = 100, accuracy = 67 WHERE weapon_name = 'Projectile Cannon Lvl 3';
UPDATE weapon_type SET shield_damage = 100, armour_damage = 50, accuracy = 47 WHERE weapon_name = 'Nijarin Ion Disrupter';
UPDATE weapon_type SET shield_damage = 100, accuracy = 69 WHERE weapon_name = 'Salvene Flux Resonator';
UPDATE weapon_type SET armour_damage = 100, accuracy = 69 WHERE weapon_name = 'Salvene Frag Missile';
UPDATE weapon_type SET shield_damage = 60, armour_damage = 60, accuracy = 58 WHERE weapon_name = 'Thevian Flux Missile';
UPDATE weapon_type SET armour_damage = 85, accuracy = 81 WHERE weapon_name = 'WQ Human Flechette Cannon';
UPDATE weapon_type SET armour_damage = 170, accuracy = 39 WHERE weapon_name = 'Ik-Thorne Rapid Fire Cannon';
UPDATE weapon_type SET armour_damage = 70, accuracy = 91 WHERE weapon_name = 'Anti-Ship Missile (Heat-Seeking)';
UPDATE weapon_type SET armour_damage = 100, accuracy = 63 WHERE weapon_name = 'Anti-Ship Missile';
UPDATE weapon_type SET armour_damage = 200, accuracy = 29 WHERE weapon_name = 'Projectile Cannon Lvl 2';
UPDATE weapon_type SET shield_damage = 65, accuracy = 94 WHERE weapon_name = 'Shield Disruptor';
UPDATE weapon_type SET armour_damage = 70, accuracy = 90 WHERE weapon_name = 'Projectile Cannon Lvl 1';
UPDATE weapon_type SET shield_damage = 35, armour_damage = 35, accuracy = 91 WHERE weapon_name = 'Small Laser';
UPDATE weapon_type SET shield_damage = 60, armour_damage = 25, accuracy = 78 WHERE weapon_name = 'Nijarin Ion Pulse Phaser';
UPDATE weapon_type SET armour_damage = 100, accuracy = 66 WHERE weapon_name = 'Thevian Rail Gun';
