UPDATE weapon_type SET cost = 340350 WHERE weapon_name = 'Holy Hand Grenade';
UPDATE weapon_type SET cost = 345500, accuracy = 35 WHERE weapon_name = 'Planetary Pulse Laser';
UPDATE weapon_type SET cost = 219750 WHERE weapon_name = 'Huge Pulse Laser';
UPDATE weapon_type SET cost = 220000 WHERE weapon_name = 'Nijarin Claymore Missile';
UPDATE weapon_type SET cost = 216000 WHERE weapon_name = 'Creonti "Big Daddy"';
UPDATE weapon_type SET cost = 210000 WHERE weapon_name = 'Thevian Shield Disperser';
UPDATE weapon_type SET cost = 185500 WHERE weapon_name = 'Little Junior Torpedo';
UPDATE weapon_type SET cost = 168000 WHERE weapon_name = 'Human Harmonic Disruptor';
UPDATE weapon_type SET cost = 166000 WHERE weapon_name = 'Alskant Focused Laser';
UPDATE weapon_type SET cost = 177000 WHERE weapon_name = 'Big Momma Torpedo Launcher';
UPDATE weapon_type SET cost = 167500 WHERE weapon_name = 'WQ Human Shield Vaporizer';
UPDATE weapon_type SET cost = 113750 WHERE weapon_name = 'Large Pulse Laser';
UPDATE weapon_type SET cost = 104000 WHERE weapon_name = 'Salvene EM Flux Cannon';
UPDATE weapon_type SET cost = 102500 WHERE weapon_name = 'Human Photon Torpedo';
UPDATE weapon_type SET cost = 100000 WHERE weapon_name = 'Nijarin Ion Phaser Beam';
UPDATE weapon_type SET cost = 101000 WHERE weapon_name = 'Insanely Large Laser';
UPDATE weapon_type SET cost = 97000 WHERE weapon_name = 'Photon Torpedo';
UPDATE weapon_type SET cost = 86500 WHERE weapon_name = 'Creonti Mole Missile';
UPDATE weapon_type SET cost = 86500 WHERE weapon_name = 'Creonti Shield Sucker';
UPDATE weapon_type SET cost = 82750 WHERE weapon_name = 'Thevian Assault Laser';
UPDATE weapon_type SET cost = 84000 WHERE weapon_name = 'Alskant Space Flechette';
UPDATE weapon_type SET cost = 80000 WHERE weapon_name = 'Ik-Thorne Burst Laser System';
UPDATE weapon_type SET cost = 79500 WHERE weapon_name = 'WQ Human Multi-Phase Laser';
UPDATE weapon_type SET cost = 76000 WHERE weapon_name = 'Pulse Laser';
UPDATE weapon_type SET cost = 59000 WHERE weapon_name = 'Nijarin Ion Disrupter';
UPDATE weapon_type SET cost = 59000 WHERE weapon_name = 'Large Laser';
UPDATE weapon_type SET cost = 53500 WHERE weapon_name = 'Alskant Pulse-Fist Missile';
UPDATE weapon_type SET cost = 50000 WHERE weapon_name = 'Salvene Flux Resonator';
UPDATE weapon_type SET cost = 51000 WHERE weapon_name = 'Projectile Cannon Lvl 4';
UPDATE weapon_type SET cost = 49750 WHERE weapon_name = 'Thevian Flux Missile';
UPDATE weapon_type SET cost = 49500 WHERE weapon_name = 'Creonti Particle Cannon';
UPDATE weapon_type SET cost = 47250 WHERE weapon_name = 'Human Space Shotgun';
UPDATE weapon_type SET cost = 47000 WHERE weapon_name = 'Ik-Thorne Cluster Missile';
UPDATE weapon_type SET cost = 46500 WHERE weapon_name = 'Salvene Frag Missile';
UPDATE weapon_type SET cost = 46000 WHERE weapon_name = 'Alskant Anti-Shield System';
UPDATE weapon_type SET cost = 47000 WHERE weapon_name = 'Torpedo Launcher';
UPDATE weapon_type SET cost = 44500 WHERE weapon_name = 'WQ Human Flechette Cannon';
UPDATE weapon_type SET cost = 45000 WHERE weapon_name = 'Advanced Shield Disruptor';
UPDATE weapon_type SET cost = 42000 WHERE weapon_name = 'Anti-Ship Missile (Guided)';
UPDATE weapon_type SET cost = 39500 WHERE weapon_name = 'Laser';
UPDATE weapon_type SET cost = 37250 WHERE weapon_name = 'Projectile Cannon Lvl 3';
UPDATE weapon_type SET cost = 34000 WHERE weapon_name = 'Ik-Thorne Accoustic Jammer';
UPDATE weapon_type SET cost = 27500 WHERE weapon_name = 'Ik-Thorne Rapid Fire Cannon';
UPDATE weapon_type SET cost = 28500 WHERE weapon_name = 'Anti-Ship Missile (Heat-Seeking)';
UPDATE weapon_type SET cost = 22250 WHERE weapon_name = 'Thevian Rail Gun';
UPDATE weapon_type SET cost = 22250 WHERE weapon_name = 'Anti-Ship Missile';
UPDATE weapon_type SET cost = 22000 WHERE weapon_name = 'Projectile Cannon Lvl 2';
UPDATE weapon_type SET cost = 20775 WHERE weapon_name = 'Nijarin Ion Pulse Phaser';
UPDATE weapon_type SET cost = 18650 WHERE weapon_name = 'Shield Disruptor';
UPDATE weapon_type SET cost = 13000 WHERE weapon_name = 'Projectile Cannon Lvl 1';
UPDATE weapon_type SET cost = 13000 WHERE weapon_name = 'Small Laser';
