<?php
/*
$AvailableMissions =& $ThisPlayer->getAvailableMissions();
if(count($AvailableMissions) > 0) {
	foreach($AvailableMissions as &$AvailableMission) {
		echo $AvailableMission['Steps'][0]['Text']; ?><br/>
		<div class="buttonA"><a href="<?php echo Globals::getAcceptMissionHREF($AvailableMission); ?>" class="buttonA"> Accept </a></div><br/><?php
	}
}

$Missions =& $ThisPlayer->getMissions();
if(count($Missions) > 0) {
	foreach($Missions as &$Mission) {
		echo $Mission['Task']['Task']; ?><br/><?php
	}
}
*/
?>