[entryPoints]
  [entryPoints.http]
    address = ":80"
  [entryPoints.https]
    address = ":443"

[providers]
  [providers.docker]
    exposedByDefault = false
    network = "frontend"
  [providers.file]
    filename = "/etc/traefik/file-provider.toml"

# We need this for the /traefik/dashboard to work
[api]
  insecure = true

[log]
  level = "INFO"

[accessLog]
