<h1>Attacker Results</h1><br />
<?php $this->includeTemplate('includes/TraderTeamCombatResults.inc',array('TraderTeamCombatResults'=>$TraderCombatResults['Attackers'])); ?><br />
<br />
<img src="images/creonti_cruiser.jpg" alt="Creonti Cruiser" title="Creonti Cruiser"><br />
<br />
<h1>Defender Results</h1><br />
<?php $this->includeTemplate('includes/TraderTeamCombatResults.inc',array('TraderTeamCombatResults'=>$TraderCombatResults['Defenders'])); ?>